% Make a list with the top 10 most eccentricity scoring electrodes
elect_list_outliers =[...
      {'p10'}      {'GB27'  };...
      {'p10'}      {'GB26'  };...
      {'p10'}      {'GB123' };...
      {'p06'}      {'G07'   };...
      {'p10'}      {'GB23'  };...
      {'p10'}      {'GB10'  };...
      {'p14'}      {'DLSL02'};...
      {'p02'}      {'Oc15'  };...
      {'p12'}      {'G01'   };...
      {'p10'}      {'GB39'  }];

% load data for each participant and plot their the outlier electrodes only
subs = unique(elect_list_outliers(:,1));
prfDir = '/home/lasse/Documents/ECoG_PRF_categories/data/prf_fits/prf_woNorm_dataA';

load(fullfile(prfDir,"sub-p14_prffits.mat"))
%%
RP2ecog_plotPRFtsfitsINDV(data2fit,stimulus,results,results.channels,...
    elect_list_outliers(strcmp(elect_list_outliers,"p14"),2))